SELECT ?material ?materialLabel ?materialDescription ?density ?melting_point ?tensile_strength ?thermal_conductivity
WHERE {
  ?material wdt:P31 wd:Q11344 .  # Instance of chemical element

  OPTIONAL { ?material wdt:P2054 ?density . }
  OPTIONAL { ?material wdt:P2101 ?melting_point . }
  OPTIONAL { ?material wdt:P2250 ?tensile_strength . }
  OPTIONAL { ?material wdt:P11426 ?thermal_conductivity . }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
LIMIT 200
